"""Single source of truth for the active TechJam demo configuration."""

from __future__ import annotations

from pathlib import Path


SHOPPING_AGENT_DIR = Path(__file__).resolve().parent
SYSTEM_DIR = SHOPPING_AGENT_DIR.parent
PROJECT_ROOT = SYSTEM_DIR.parent

CATALOG_PATH = PROJECT_ROOT / "techjam-conversational-search" / "data" / "catalog.jsonl"
EMBEDDING_CACHE_DIR = SHOPPING_AGENT_DIR / "embedding_cache"
MEMORY_STORE_PATH = SHOPPING_AGENT_DIR / ".demo_state" / "vector_memory.json"

OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"
OPENAI_EMBEDDING_DIMENSIONS = 3072
OPENAI_CHAT_MODEL = "gpt-4o-mini"
DEEPSEEK_CHAT_MODEL = "deepseek-chat"

RELEVANCE_THRESHOLD = 0.20
BUYING_CURRENT_WEIGHT = 0.80
BUYING_MEMORY_WEIGHT = 0.20
BROWSING_CURRENT_WEIGHT = 0.20
BROWSING_MEMORY_WEIGHT = 0.80
EWMA_ALPHA = 0.30
DEMO_TOP_K = 5
EXPECTED_CATALOG_ROWS = 50_000


__all__ = [
    "BROWSING_CURRENT_WEIGHT",
    "BROWSING_MEMORY_WEIGHT",
    "BUYING_CURRENT_WEIGHT",
    "BUYING_MEMORY_WEIGHT",
    "CATALOG_PATH",
    "DEMO_TOP_K",
    "DEEPSEEK_CHAT_MODEL",
    "EMBEDDING_CACHE_DIR",
    "EWMA_ALPHA",
    "EXPECTED_CATALOG_ROWS",
    "MEMORY_STORE_PATH",
    "OPENAI_CHAT_MODEL",
    "OPENAI_EMBEDDING_DIMENSIONS",
    "OPENAI_EMBEDDING_MODEL",
    "PROJECT_ROOT",
    "RELEVANCE_THRESHOLD",
    "SHOPPING_AGENT_DIR",
    "SYSTEM_DIR",
]
